name: Zola on GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TailwindCSS
        run: |
          curl -sLo tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss
          sudo mv tailwindcss /usr/local/bin/

      - name: Download DaisyUI dependencies
        run: |
          curl -sLo src/daisyui.js https://github.com/saadeghi/daisyui/releases/latest/download/daisyui.js
          curl -sLo src/daisyui-theme.js https://github.com/saadeghi/daisyui/releases/latest/download/daisyui-theme.js

      - name: Build CSS
        run: tailwindcss -i src/main.css -o static/css/main.css --minify

      - name: Add CNAME file
        run: echo "goyo.hahwul.com" > static/CNAME

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check internal links
        if: github.event_name == 'pull_request'
        run: |
          zola check --skip-external-links
